# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8630f1ead812ad060c3268516787b525f38e1c7236fe3ed8ba26a4291fa6bae89b007431494ba8ff7abec01cef8eaa698b89986be397a9854cc93f907105740

test:
  secret_key_base: b2f7f89eface9a3ac0eee9ba631589cd43d07e2e61e2708fda24743b018635b59dcbc728be3dd5c0692d5ae4804d25af71ee1942d70058bc3c5fe6b1c846173b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
